name: assets_challenge
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  slang: 4.7.3
  slang_flutter: 4.7.0
  json_annotation: 4.9.0
  equatable: 2.0.7
  get_it: 8.0.3
  flutter_svg: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.5.4
  slang_build_runner: ^4.7.0
  json_serializable: 6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/svg/asset.svg
    - assets/svg/component.svg
    - assets/svg/location.svg
    - assets/svg/tractian.svg
